ALT_FOR = "alt_for"
BIRTH_PLACE = "birth_place"
BIRTH_PLACE_MD = "birth_place_md"
DATE = "date"
DATE_MD = "date_md"
FOR = "for"
LOCATION = "location"
LOCATION_MD = "location_md"
FRIENDLY_LOCATION = "friendly_location"
JSP_URL = "jsp_url"
NOTES = "notes"
NOTES_MD = "notes_md"
PLUS_NOTES = "+notes"
PLUS_NOTES_MD = "+notes_md"
OUTCOME = "outcome"
OUTCOME_MD = "outcome_md"
RECORDING_URL = "recording_url"
TAGLINE_MD = "tagline_md"
UNIT = "unit"
UNIT_MD = "unit_md"

DESCRIPTIONS = {
    PLUS_NOTES: "Additional notes beyond those provided in '%s' or autogenerated." % NOTES
}
